CREATE USER flightsystem IDENTIFIED BY flightsystempass;
GRANT CONNECT, RESOURCE, CREATE CLUSTER, QUERY REWRITE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SESSION, CREATE SYNONYM, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW, CREATE LIBRARY, UNLIMITED TABLESPACE TO flightsystem;
COMMIT;

